language: python
virtualenv:
    system_site_packages: true
python:
    - 2.7
before_install:
    - sudo apt-get install python-qt4
script:
    - "python setup.py test"
notifications:
  email:
    - sebastianr213@gmail.com
    - gustavosilvadesousa@gmail.com